<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Deskestro.Windows.TestApp</AssemblyName>
    <ApplicationIcon>..\..\Resources\Deskestro.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
